version: "3"
tasks:
  dev:
    desc: Start the developer instance
    cmds:
      - npm run start

  prod:
    desc: Start the production instance (on your mobile device, open up `Go Expo` app and connect to this instance)
    cmds:
      - npx expo start --no-dev --minify

  ios:
    desc: Start the developer instance using iOS using Simulator and building native image
    cmds:
      - npx expo run:ios

  ios-device:
    desc: Start the production instance for iOS using physical device (please make sure your device is connected via cable and registered with Apple Developer program)
    cmds:
      - npx expo run:ios --device --configuration Release

  ios-build:
    desc: Build the iOS app using latest expo app.json
    cmds:
      - npx expo prebuild --platform ios --clean

  ios-xcode:
    desc: Open iOS workspace in Xcode. Run this code after executing `iso-build`.
    cmds:
      - xed ios

  android:
    desc: Start the developer instance for Android
    cmds:
      - export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
      - export ANDROID_HOME=$HOME/Library/Android/sdk
      - export PATH=$PATH:$ANDROID_HOME/emulator
      - export PATH=$PATH:$ANDROID_HOME/platform-tools
      - npx expo run:android

  android-build:
    desc: (Dangerous - will delete local keystore!) Build the Android app using latest expo app.json
    cmds:
      - npx expo prebuild --platform android --clean

  android-v2:
    desc: Start the developer instance for Android
    cmds:
      - export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
      - export ANDROID_HOME=$HOME/Library/Android/sdk
      - export PATH=$PATH:$ANDROID_HOME/emulator
      - export PATH=$PATH:$ANDROID_HOME/platform-tools
      - npx expo prebuild --platform android
      - npx expo run:android

  doctor:
    desc: Perform a check on our expo codebase to discover an potential issue(s)
    cmds:
      - npx expo-doctor

  upgrade:
    desc: Uprade our core libraries
    cmds:
      - npx expo install react-native@latest
      - npx expo install expo@latest
      - npx expo install react-native-reanimated@latest
      - npx expo install --check

  reset:
    desc: Reset the project to its initial state
    cmds:
      - npm run reset-project

  clean:
    desc: Clean the project's library dependencies.
    cmds:
      # Remove build cache
      - rm -rf ios/build

      # Remove derived data
      - rm -rf ~/Library/Developer/Xcode/DerivedData/comiccoinpublicfaucet-*

      # # Remove iOS pods and reinstall
      # - cd ios
      # - rm -rf Pods
      # - rm -rf Podfile.lock
      # - pod install
      # - cd ..

      # Clean the Expo project
      # - npx expo clean

      # Reinstall node modules
      - rm -rf node_modules
      - npm install

      # Prebuild the iOS and Android folders
      - npx expo prebuild --clean
      - cd ios && pod install && cd ..

  undelast:
    desc: Undue last commit which was not pushed. Special thanks to https://www.nobledesktop.com/learn/git/undo-changes.
    cmds:
      - git reset --soft HEAD~
