version: '3'

tasks:
  start:
    desc: Start the backend in developer mode
    cmds:
      - docker-compose -p comiccoin_authority -f dev.docker-compose.yml up

  end:
    desc: Stop the backend in developer mode
    cmds:
      - docker-compose -p comiccoin_authority -f dev.docker-compose.yml down

  console:
    desc: Open console in (developer mode) running backend
    cmds:
      - docker exec -it comiccoin_authority bash

  dockerlogin:
    desc: (DevOps only) Command will log in your developer's machine with the private docker registry.
    cmds:
      -  docker login registry.digitalocean.com

  dockerlogout:
    desc: (DevOps only) Command will log out of the private docker registry. (Important step if you are using other private docker registries)
    cmds:
      - docker logout registry.digitalocean.com

  dockerdeployprod:
    desc: (DevOps only) Command will build the production container of this project and deploy to the private docker registry.
    cmds:
      - docker build -f Dockerfile --rm -t registry.digitalocean.com/ssp/comiccoin-authority:prod --platform linux/amd64 .
      - docker tag registry.digitalocean.com/ssp/comiccoin-authority:prod registry.digitalocean.com/ssp/comiccoin-authority:prod
      - docker push registry.digitalocean.com/ssp/comiccoin-authority:prod

  dockerdeployqa:
    desc: (DevOps only) Command will build the quality assurance (QA) container of this project and deploy to the private docker registry.
    cmds:
      - docker build -f Dockerfile --rm -t registry.digitalocean.com/ssp/comiccoin-authority:qa --platform linux/amd64 .
      - docker tag registry.digitalocean.com/ssp/comiccoin-authority:qa registry.digitalocean.com/ssp/comiccoin-authority:qa
      - docker push registry.digitalocean.com/ssp/comiccoin-authority:qa

  clean:
    cmds:
      - go clean -cache
      - go clean -modcache

  osxlisten:
    desc: "See what apps apps are running and listing to what ports. Aftwords use for example: kill -9 4097"
    cmds:
      - sudo lsof -nPi -sTCP:LISTEN
