version: '3'

tasks:
  start:
    desc: Start the cloud backend in developer mode
    cmds:
      - go work use ./cloud/comiccoin-gateway
      - cd ./cloud/comiccoin-gateway
      - docker-compose -p comiccoin -f ./cloud/comiccoin/dev.docker-compose.yml up

  gatewayconsole:
    desc: Open console in (developer mode) running cloud backend
    cmds:
      - docker exec -it comiccoin bash
