version: "3"

tasks:
  comiccoin-dev:
    desc: Start the cloud services backend in developer mode
    cmds:
      - go work use ./cloud/comiccoin
      - docker-compose -p comiccoin -f ./cloud/comiccoin/dev.docker-compose.yml up

  comiccoin-console:
    desc: Open console in (developer mode) running cloud services backend
    cmds:
      - docker exec -it comiccoin bash
