version: "3"

tasks:
  distlist:
    desc: List of possible platforms and chipsets to build with.
    cmds:
      - go tool dist list

  buildlinux:
    desc: Build a linux executable.
    cmds:
      - GOOS=linux GOARCH=amd64 go build -ldflags="-X 'main.Version=v1.0.0-beta'" -o ./build/comiccoin-v1.0.0-beta-linux_amd64 .

  buildmac:
    desc: Build a Apple Mac executable.
    cmds:
      - GOOS=darwin GOARCH=arm64 go build -ldflags="-X 'main.Version=v1.0.0-beta'" -o ./build/comiccoin-v1.0.0-beta-mac .

  buildwin:
    desc: Build a Microsoft Winows executable.
    cmds:
      - GOOS=windows GOARCH=arm64 go build -ldflags="-X 'main.Version=v1.0.0-beta'" -o ./build/comiccoin-v1.0.0-beta-win_amd64 .
