version: "3"
tasks:
  start:
    desc: Start the developer instance
    cmds:
      - npm run start

  xcode:
    desc: Open iOS workspace in Xcode
    cmds:
      - xed ios

  ios:
    desc: Start the developer instance for iOS using Simulator
    cmds:
      - npx expo run:ios

  ios-build:
    desc: (Dangerous - will delete previous xcode project!) Build the iOS app using latest expo app.json
    cmds:
      - npx expo prebuild --platform ios --clean

  ios_device:
    desc: Start the developer instance for iOS using physical device (please make sure your device is connected via cable and registered with Apple Developer program)
    cmds:
      - npx expo run:ios --device

  android:
    desc: Start the developer instance for Android
    cmds:
      - export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
      - export ANDROID_HOME=$HOME/Library/Android/sdk
      - export PATH=$PATH:$ANDROID_HOME/emulator
      - export PATH=$PATH:$ANDROID_HOME/platform-tools
      - npx expo run:android

  android-build:
    desc: (Dangerous - will delete local keystore!) Build the Android app using latest expo app.json
    cmds:
      - npx expo prebuild --platform android --clean

  doctor:
    desc: Perform a check on our expo codebase to discover an potential issue(s)
    cmds:
      - npx expo-doctor

  upgrade:
    desc: Uprade our core libraries
    cmds:
      - npm install react-native@latest
      - npm install expo@latest
      - npm install react-native-reanimated@latest

  reset:
    desc: Reset the project to its initial state
    cmds:
      - npm run reset-project

  llmcat:
    desc: "Concatinate our project into LLM friendly single text (dependent on third-party app called `crev`)"
    cmds:
      - crev bundle
