version: "3"
tasks:
  start:
    desc: Start the developer instance
    cmds:
      - npm run start

  xcode:
    desc: Open iOS workspace in Xcode
    cmds:
      - xed ios

  ios:
    desc: Start the developer instance for iOS
    cmds:
      - npm run ios
