// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDataDirectoryFromDialog():Promise<string>;

export function GetDataDirectoryFromPreferences():Promise<string>;

export function GetDefaultDataDirectory():Promise<string>;

export function GetIsBlockhainNodeRunning():Promise<boolean>;

export function GetNFTStorageAddressFromPreferences():Promise<string>;

export function GetPreferences():Promise<main.Preferences>;

export function SaveDataDirectory(arg1:string):Promise<void>;

export function SetAuthorityAddress(arg1:string):Promise<void>;

export function SetNFTStorageAddress(arg1:string):Promise<void>;

export function ShutdownApp():Promise<void>;
