// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDataDirectoryFromDialog() {
  return window['go']['main']['App']['GetDataDirectoryFromDialog']();
}

export function GetDataDirectoryFromPreferences() {
  return window['go']['main']['App']['GetDataDirectoryFromPreferences']();
}

export function GetDefaultDataDirectory() {
  return window['go']['main']['App']['GetDefaultDataDirectory']();
}

export function GetIsBlockhainNodeRunning() {
  return window['go']['main']['App']['GetIsBlockhainNodeRunning']();
}

export function GetNFTStorageAPIKeyFromPreferences() {
  return window['go']['main']['App']['GetNFTStorageAPIKeyFromPreferences']();
}

export function GetNFTStorageAddressFromPreferences() {
  return window['go']['main']['App']['GetNFTStorageAddressFromPreferences']();
}

export function GetPreferences() {
  return window['go']['main']['App']['GetPreferences']();
}

export function SaveDataDirectory(arg1) {
  return window['go']['main']['App']['SaveDataDirectory'](arg1);
}

export function SaveNFTStoreConfigVariables(arg1, arg2) {
  return window['go']['main']['App']['SaveNFTStoreConfigVariables'](arg1, arg2);
}

export function SetAuthorityAddress(arg1) {
  return window['go']['main']['App']['SetAuthorityAddress'](arg1);
}

export function SetNFTStorageAPIKey(arg1) {
  return window['go']['main']['App']['SetNFTStorageAPIKey'](arg1);
}

export function SetNFTStorageAddress(arg1) {
  return window['go']['main']['App']['SetNFTStorageAddress'](arg1);
}

export function ShutdownApp() {
  return window['go']['main']['App']['ShutdownApp']();
}
