// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateToken(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string):Promise<main.Token>;

export function GetDataDirectoryFromDialog():Promise<string>;

export function GetDataDirectoryFromPreferences():Promise<string>;

export function GetDefaultDataDirectory():Promise<string>;

export function GetFileViaIPFS(arg1:string):Promise<main.NFTAsset>;

export function GetImageFilePathFromDialog():Promise<string>;

export function GetIsBlockhainNodeRunning():Promise<boolean>;

export function GetIsNFTAssetStoreRunning():Promise<boolean>;

export function GetNFTStorageAPIKeyFromPreferences():Promise<string>;

export function GetNFTStorageAddressFromPreferences():Promise<string>;

export function GetPreferences():Promise<main.Preferences>;

export function GetToken(arg1:number):Promise<main.Token>;

export function GetTokens():Promise<Array<main.Token>>;

export function GetVideoFilePathFromDialog():Promise<string>;

export function SaveAuthorityStoreConfigVariables(arg1:string,arg2:string):Promise<void>;

export function SaveDataDirectory(arg1:string):Promise<void>;

export function SaveNFTStoreConfigVariables(arg1:string,arg2:string):Promise<void>;

export function SetAuthorityAPIKey(arg1:string):Promise<void>;

export function SetAuthorityAddress(arg1:string):Promise<void>;

export function SetNFTStorageAPIKey(arg1:string):Promise<void>;

export function SetNFTStorageAddress(arg1:string):Promise<void>;

export function ShutdownApp():Promise<void>;
