// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateToken(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['CreateToken'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function GetDataDirectoryFromDialog() {
  return window['go']['main']['App']['GetDataDirectoryFromDialog']();
}

export function GetDataDirectoryFromPreferences() {
  return window['go']['main']['App']['GetDataDirectoryFromPreferences']();
}

export function GetDefaultDataDirectory() {
  return window['go']['main']['App']['GetDefaultDataDirectory']();
}

export function GetFileViaIPFS(arg1) {
  return window['go']['main']['App']['GetFileViaIPFS'](arg1);
}

export function GetImageFilePathFromDialog() {
  return window['go']['main']['App']['GetImageFilePathFromDialog']();
}

export function GetIsBlockhainNodeRunning() {
  return window['go']['main']['App']['GetIsBlockhainNodeRunning']();
}

export function GetIsNFTAssetStoreRunning() {
  return window['go']['main']['App']['GetIsNFTAssetStoreRunning']();
}

export function GetNFTStorageAPIKeyFromPreferences() {
  return window['go']['main']['App']['GetNFTStorageAPIKeyFromPreferences']();
}

export function GetNFTStorageAddressFromPreferences() {
  return window['go']['main']['App']['GetNFTStorageAddressFromPreferences']();
}

export function GetPreferences() {
  return window['go']['main']['App']['GetPreferences']();
}

export function GetToken(arg1) {
  return window['go']['main']['App']['GetToken'](arg1);
}

export function GetTokens() {
  return window['go']['main']['App']['GetTokens']();
}

export function GetVideoFilePathFromDialog() {
  return window['go']['main']['App']['GetVideoFilePathFromDialog']();
}

export function SaveAuthorityStoreConfigVariables(arg1, arg2) {
  return window['go']['main']['App']['SaveAuthorityStoreConfigVariables'](arg1, arg2);
}

export function SaveDataDirectory(arg1) {
  return window['go']['main']['App']['SaveDataDirectory'](arg1);
}

export function SaveNFTStoreConfigVariables(arg1, arg2) {
  return window['go']['main']['App']['SaveNFTStoreConfigVariables'](arg1, arg2);
}

export function SetAuthorityAPIKey(arg1) {
  return window['go']['main']['App']['SetAuthorityAPIKey'](arg1);
}

export function SetAuthorityAddress(arg1) {
  return window['go']['main']['App']['SetAuthorityAddress'](arg1);
}

export function SetNFTStorageAPIKey(arg1) {
  return window['go']['main']['App']['SetNFTStorageAPIKey'](arg1);
}

export function SetNFTStorageAddress(arg1) {
  return window['go']['main']['App']['SetNFTStorageAddress'](arg1);
}

export function ShutdownApp() {
  return window['go']['main']['App']['ShutdownApp']();
}
