#############
# HOW TO USE:
#############
# The purpose of this docker-compose is to setup our application which is
# dependent on the `MongoDB` database cluster running concurrently with this
# server for developer purposes. This configuration has hot-reloading activated.
# This is docker-compose is used for developers only.
#
# ------------------------------------------------------------------------------
# $ docker-compose -p comiccoin_publicfaucet -f dev.docker-compose.yml up   #
# ------------------------------------------------------------------------------
#

services:
  db1:
    container_name: comiccoin_publicfaucet_db1
    image: mongo
    command:
      [
        "--replSet",
        "rs0",
        "--bind_ip_all",
        "--port",
        "38017",
        "--quiet",
        "--logpath",
        "/dev/null",
      ]
    restart: unless-stopped
    ports:
      - 38017:38017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:38017',priority:1},{_id:1,host:'host.docker.internal:38018',priority:0.5},{_id:2,host:'host.docker.internal:38019',priority:0.5}]}) }" | mongosh --port 38017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - "./data/db1/db:/data/db"
      - "./data/db1/configdb:/data/configdb"

  db2:
    container_name: comiccoin_publicfaucet_db2
    image: mongo
    command:
      [
        "--replSet",
        "rs0",
        "--bind_ip_all",
        "--port",
        "38018",
        "--quiet",
        "--logpath",
        "/dev/null",
      ]
    restart: unless-stopped
    ports:
      - 38018:38018
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "./data/db2/db:/data/db"
      - "./data/db2/configdb:/data/configdb"

  db3:
    container_name: comiccoin_publicfaucet_db3
    image: mongo
    command:
      [
        "--replSet",
        "rs0",
        "--bind_ip_all",
        "--port",
        "38019",
        "--quiet",
        "--logpath",
        "/dev/null",
      ]
    restart: unless-stopped
    ports:
      - 38019:38019
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "./data/db3/db:/data/db"
      - "./data/db3/configdb:/data/configdb"

  mongo-express:
    container_name: comiccoin_publicfaucet_db_admin
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_SERVER=db1
      - ME_CONFIG_MONGODB_PORT=38017
      - ME_CONFIG_MONGODB_URI=mongodb://db1:38017,db2:38018,db3:38019/?replicaSet=rs0
    ports:
      - "9099:8081"
    depends_on:
      - db1
      - db2
      - db3
    links:
      - db1
      - db2
      - db3
    restart: unless-stopped

  # The main application.
  app:
    container_name: comiccoin_publicfaucet
    stdin_open: true
    environment:
      COMICCOIN_PUBLICFAUCET_APP_DATA_DIRECTORY: ${COMICCOIN_PUBLICFAUCET_APP_DATA_DIRECTORY}
      COMICCOIN_PUBLICFAUCET_APP_FRONTEND_DOMAIN: ${COMICCOIN_PUBLICFAUCET_APP_FRONTEND_DOMAIN}
      COMICCOIN_PUBLICFAUCET_APP_BACKEND_DOMAIN: ${COMICCOIN_PUBLICFAUCET_APP_BACKEND_DOMAIN}
      COMICCOIN_PUBLICFAUCET_WALLET_ADDRESS: ${COMICCOIN_PUBLICFAUCET_WALLET_ADDRESS}
      COMICCOIN_PUBLICFAUCET_WALLET_MNEMONIC: ${COMICCOIN_PUBLICFAUCET_WALLET_MNEMONIC}
      COMICCOIN_PUBLICFAUCET_WALLET_PATH: ${COMICCOIN_PUBLICFAUCET_WALLET_PATH}
      COMICCOIN_PUBLICFAUCET_TENANT_ID: ${COMICCOIN_PUBLICFAUCET_TENANT_ID}
      COMICCOIN_PUBLICFAUCET_AUTHORITY_HTTP_ADDRESS: ${COMICCOIN_PUBLICFAUCET_AUTHORITY_HTTP_ADDRESS}
      COMICCOIN_PUBLICFAUCET_NFTSTORAGE_HTTP_ADDRESS: ${COMICCOIN_PUBLICFAUCET_NFTSTORAGE_HTTP_ADDRESS}
      COMICCOIN_PUBLICFAUCET_HMAC_SECRET: ${COMICCOIN_PUBLICFAUCET_HMAC_SECRET}
      COMICCOIN_PUBLICFAUCET_IP: 0.0.0.0
      COMICCOIN_PUBLICFAUCET_PORT: 8080
      COMICCOIN_PUBLICFAUCET_APP_REGISTRATION_COINS_REWARD: ${COMICCOIN_PUBLICFAUCET_APP_REGISTRATION_COINS_REWARD}
      COMICCOIN_PUBLICFAUCET_APP_COMIC_SUBMISSION_COINS_REWARD: ${COMICCOIN_PUBLICFAUCET_APP_COMIC_SUBMISSION_COINS_REWARD}
      COMICCOIN_PUBLICFAUCET_APP_GEOLITE_DB_PATH: ${COMICCOIN_PUBLICFAUCET_APP_GEOLITE_DB_PATH}
      COMICCOIN_PUBLICFAUCET_APP_BANNED_COUNTRIES: ${COMICCOIN_PUBLICFAUCET_APP_BANNED_COUNTRIES}
      COMICCOIN_PUBLICFAUCET_DB_URI: mongodb://db1:38017,db2:38018,db3:38019/?replicaSet=rs0 # This is dependent on the configuration in our docker-compose file (see above).
      COMICCOIN_PUBLICFAUCET_DB_NAME: ${COMICCOIN_PUBLICFAUCET_DB_NAME}
      COMICCOIN_PUBLICFAUCET_BLOCKCHAIN_CHAIN_ID: ${COMICCOIN_PUBLICFAUCET_BLOCKCHAIN_CHAIN_ID}
      COMICCOIN_PUBLICFAUCET_BLOCKCHAIN_TRANS_PER_BLOCK: ${COMICCOIN_PUBLICFAUCET_BLOCKCHAIN_TRANS_PER_BLOCK}
      COMICCOIN_PUBLICFAUCET_BLOCKCHAIN_DIFFICULTY: ${COMICCOIN_PUBLICFAUCET_BLOCKCHAIN_DIFFICULTY}
      COMICCOIN_PUBLICFAUCET_BLOCKCHAIN_TRANSACTION_FEE: ${COMICCOIN_PUBLICFAUCET_BLOCKCHAIN_TRANSACTION_FEE}
      COMICCOIN_PUBLICFAUCET_MAILGUN_API_KEY: ${COMICCOIN_PUBLICFAUCET_MAILGUN_API_KEY}
      COMICCOIN_PUBLICFAUCET_MAILGUN_DOMAIN: ${COMICCOIN_PUBLICFAUCET_MAILGUN_DOMAIN}
      COMICCOIN_PUBLICFAUCET_MAILGUN_API_BASE: ${COMICCOIN_PUBLICFAUCET_MAILGUN_API_BASE}
      COMICCOIN_PUBLICFAUCET_MAILGUN_SENDER_EMAIL: ${COMICCOIN_PUBLICFAUCET_MAILGUN_SENDER_EMAIL}
      COMICCOIN_PUBLICFAUCET_MAILGUN_MAINTENANCE_EMAIL: ${COMICCOIN_PUBLICFAUCET_MAILGUN_MAINTENANCE_EMAIL}
      COMICCOIN_PUBLICFAUCET_AWS_ACCESS_KEY: ${COMICCOIN_PUBLICFAUCET_AWS_ACCESS_KEY}
      COMICCOIN_PUBLICFAUCET_AWS_SECRET_KEY: ${COMICCOIN_PUBLICFAUCET_AWS_SECRET_KEY}
      COMICCOIN_PUBLICFAUCET_AWS_ENDPOINT: ${COMICCOIN_PUBLICFAUCET_AWS_ENDPOINT}
      COMICCOIN_PUBLICFAUCET_AWS_REGION: ${COMICCOIN_PUBLICFAUCET_AWS_REGION}
      COMICCOIN_PUBLICFAUCET_AWS_BUCKET_NAME: ${COMICCOIN_PUBLICFAUCET_AWS_BUCKET_NAME}
      COMICCOIN_PUBLICFAUCET_OAUTH_SERVER_URL: ${COMICCOIN_PUBLICFAUCET_OAUTH_SERVER_URL}
      COMICCOIN_PUBLICFAUCET_OAUTH_CLIENT_ID: ${COMICCOIN_PUBLICFAUCET_OAUTH_CLIENT_ID}
      COMICCOIN_PUBLICFAUCET_OAUTH_CLIENT_SECRET: ${COMICCOIN_PUBLICFAUCET_OAUTH_CLIENT_SECRET}
      COMICCOIN_PUBLICFAUCET_OAUTH_REDIRECT_URI: ${COMICCOIN_PUBLICFAUCET_OAUTH_REDIRECT_URI}
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    restart: unless-stopped
    ports:
      - "9090:8080" # Server
    depends_on:
      - db1
      - db2
      - db3
    links:
      - db1
      - db2
      - db3
    volumes: # Connect the local filesystem with the docker filesystem. DO NOT REMOVE.
      - ./:/go/src/github.com/comiccoin-network/monorepo/cloud/comiccoin-publicfaucet # IMPORTANT: Required for hotreload via `CompileDaemon`.
    cap_add: # See: https://github.com/AdguardTeam/AdGuardHome/issues/5903
      - NET_ADMIN
    extra_hosts:
      - "host.docker.internal:host-gateway"
