#############
# HOW TO USE:
#############
# The purpose of this docker-compose is to setup our application which is
# dependent on the `MongoDB` database cluster running concurrently with this
# server for user-acceptance testing purposes.
#
# ------------------------------------------------------------------------------
# $ docker-compose -p comiccoin_publicfaucet -f docker-compose.yml up   #
# ------------------------------------------------------------------------------
#

services:
  db1:
    container_name: comiccoin_publicfaucet_db1
    image: mongo:8
    command:
      [
        "--replSet",
        "rs0",
        "--bind_ip_all",
        "--port",
        "27017",
        "--quiet",
        "--logpath",
        "/dev/null",
      ]
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-publicfaucet"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017',priority:1},{_id:1,host:'host.docker.internal:27018',priority:0.5},{_id:2,host:'host.docker.internal:27019',priority:0.5}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - "./data/db1/db:/data/db"
      - "./data/db1/configdb:/data/configdb"

  db2:
    container_name: comiccoin_publicfaucet_db2
    image: mongo:8
    command:
      [
        "--replSet",
        "rs0",
        "--bind_ip_all",
        "--port",
        "27018",
        "--quiet",
        "--logpath",
        "/dev/null",
      ]
    ports:
      - 27018:27018
    extra_hosts:
      - "host.docker.internal:host-publicfaucet"
    volumes:
      - "./data/db2/db:/data/db"
      - "./data/db2/configdb:/data/configdb"

  db3:
    container_name: comiccoin_publicfaucet_db3
    image: mongo:8
    command:
      [
        "--replSet",
        "rs0",
        "--bind_ip_all",
        "--port",
        "27019",
        "--quiet",
        "--logpath",
        "/dev/null",
      ]
    ports:
      - 27019:27019
    extra_hosts:
      - "host.docker.internal:host-publicfaucet"
    volumes:
      - "./data/db3/db:/data/db"
      - "./data/db3/configdb:/data/configdb"

  # The main application.
  app:
    container_name: comiccoin_publicfaucet
    stdin_open: true
    environment:
      COMICCOIN_PUBLICFAUCETAPP_DATA_DIRECTORY: ${COMICCOIN_PUBLICFAUCETAPP_DATA_DIRECTORY}
      COMICCOIN_PUBLICFAUCETAPP_FRONTEND_DOMAIN: ${COMICCOIN_PUBLICFAUCETAPP_FRONTEND_DOMAIN}
      COMICCOIN_PUBLICFAUCETAPP_BACKEND_DOMAIN: ${COMICCOIN_PUBLICFAUCETAPP_BACKEND_DOMAIN}
      COMICCOIN_PUBLICFAUCETWALLET_ADDRESS: ${COMICCOIN_PUBLICFAUCETWALLET_ADDRESS}
      COMICCOIN_PUBLICFAUCETWALLET_PASSWORD: ${COMICCOIN_PUBLICFAUCETWALLET_PASSWORD}
      COMICCOIN_PUBLICFAUCETTENANT_ID: ${COMICCOIN_PUBLICFAUCETTENANT_ID}
      COMICCOIN_PUBLICFAUCETAUTHORITY_HTTP_ADDRESS: ${COMICCOIN_PUBLICFAUCETAUTHORITY_HTTP_ADDRESS}
      COMICCOIN_PUBLICFAUCETNFTSTORAGE_HTTP_ADDRESS: ${COMICCOIN_PUBLICFAUCETNFTSTORAGE_HTTP_ADDRESS}
      COMICCOIN_PUBLICFAUCETHMAC_SECRET: ${COMICCOIN_PUBLICFAUCETHMAC_SECRET}
      COMICCOIN_PUBLICFAUCETIP: 0.0.0.0
      COMICCOIN_PUBLICFAUCETPORT: 8000
      COMICCOIN_PUBLICFAUCETAPP_REGISTRATION_COINS_REWARD: ${COMICCOIN_PUBLICFAUCETAPP_REGISTRATION_COINS_REWARD}
      COMICCOIN_PUBLICFAUCETAPP_COMIC_SUBMISSION_COINS_REWARD: ${COMICCOIN_PUBLICFAUCETAPP_COMIC_SUBMISSION_COINS_REWARD}
      COMICCOIN_PUBLICFAUCETDB_URI: mongodb://db1:37017,db2:37018,db3:37019/?replicaSet=rs0 # This is dependent on the configuration in our docker-compose file (see above).
      COMICCOIN_PUBLICFAUCETDB_NAME: ${COMICCOIN_PUBLICFAUCETDB_NAME}
      COMICCOIN_PUBLICFAUCETBLOCKCHAIN_CHAIN_ID: ${COMICCOIN_PUBLICFAUCETBLOCKCHAIN_CHAIN_ID}
      COMICCOIN_PUBLICFAUCETBLOCKCHAIN_TRANS_PER_BLOCK: ${COMICCOIN_PUBLICFAUCETBLOCKCHAIN_TRANS_PER_BLOCK}
      COMICCOIN_PUBLICFAUCETBLOCKCHAIN_DIFFICULTY: ${COMICCOIN_PUBLICFAUCETBLOCKCHAIN_DIFFICULTY}
      COMICCOIN_PUBLICFAUCETBLOCKCHAIN_TRANSACTION_FEE: ${COMICCOIN_PUBLICFAUCETBLOCKCHAIN_TRANSACTION_FEE}
      COMICCOIN_PUBLICFAUCETMAILGUN_API_KEY: ${COMICCOIN_PUBLICFAUCETMAILGUN_API_KEY}
      COMICCOIN_PUBLICFAUCETMAILGUN_DOMAIN: ${COMICCOIN_PUBLICFAUCETMAILGUN_DOMAIN}
      COMICCOIN_PUBLICFAUCETMAILGUN_API_BASE: ${COMICCOIN_PUBLICFAUCETMAILGUN_API_BASE}
      COMICCOIN_PUBLICFAUCETMAILGUN_SENDER_EMAIL: ${COMICCOIN_PUBLICFAUCETMAILGUN_SENDER_EMAIL}
      COMICCOIN_PUBLICFAUCETMAILGUN_MAINTENANCE_EMAIL: ${COMICCOIN_PUBLICFAUCETMAILGUN_MAINTENANCE_EMAIL}
      COMICCOIN_PUBLICFAUCETAWS_ACCESS_KEY: ${COMICCOIN_PUBLICFAUCETAWS_ACCESS_KEY}
      COMICCOIN_PUBLICFAUCETAWS_SECRET_KEY: ${COMICCOIN_PUBLICFAUCETAWS_SECRET_KEY}
      COMICCOIN_PUBLICFAUCETAWS_ENDPOINT: ${COMICCOIN_PUBLICFAUCETAWS_ENDPOINT}
      COMICCOIN_PUBLICFAUCETAWS_REGION: ${COMICCOIN_PUBLICFAUCETAWS_REGION}
      COMICCOIN_PUBLICFAUCETAWS_BUCKET_NAME: ${COMICCOIN_PUBLICFAUCETAWS_BUCKET_NAME}
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db1
      - db2
      - db3
    links:
      - db1
      - db2
      - db3
    volumes: # Connect the local filesystem with the docker filesystem. DO NOT REMOVE.
      - ./:/go/src/github.com/comiccoin-network/monorepo/cloud/comiccoin-publicfaucet # IMPORTANT: Required for hotreload via `CompileDaemon`.
