version: "3"

tasks:
  distlist:
    desc: List of possible platforms and chipsets to build with.
    cmds:
      - go tool dist list

  buildlinux:
    desc: Build a linux executable.
    cmds:
      - GOOS=linux GOARCH=amd64 wails build -clean -o comiccoin-wallet

  buildmac:
    desc: Build a Apple Mac executable.
    cmds:
      - GOOS=darwin GOARCH=arm64 wails build -clean -o comiccoin-wallet

  buildwin:
    desc: Build a Microsoft Winows executable.
    cmds:
      - GOOS=windows GOARCH=amd64 wails build -nsis

  start:
    desc: Begin and run the daemon in the foreground of maintaining connection with the ComicCoin blockchain network.
    cmds:
      - wails dev
