version: "3"

vars:
  APP_NAME: comiccoin-wallet
  DISPLAY_NAME: ComicCoin Wallet
  VERSION: 1.0.1

tasks:
  distlist:
    desc: List of possible platforms and chipsets to build with.
    cmds:
      - go tool dist list

  buildmac:
    desc: Build a Apple Mac executable.

  buildwin:
    desc: Build a Microsoft Winows executable.
    cmds:
      - GOOS=windows GOARCH=amd64 wails build -nsis

  start:
    desc: Begin and run the daemon in the foreground of maintaining connection with the ComicCoin blockchain network.
    cmds:
      - wails dev

  buildlinux:
    desc: Build a linux executable.
    cmds:
      - GOOS=linux GOARCH=amd64 wails build

  create-desktop:
    desc: Create desktop entry file
    cmds:
      - |
        cat > desktop.desktop << EOL
        [Desktop Entry]
        Name={{.DISPLAY_NAME}}
        Exec=comiccoin-wallet
        Icon=comiccoin-wallet
        Type=Application
        Categories=Finance;Network;Blockchain;
        Comment=Official desktop wallet for ComicCoin
        EOL

  # create-install-instructions:
  #   desc: Create installation instructions
  #   cmds:
  #     - |
  #       cat > dist/README.md << EOL
  #       # ComicCoin Wallet Installation
  #
  #       ## Ubuntu/Debian:
  #       ```bash
  #       wget https://example.com/downloads/comiccoin-wallet_{{.VERSION}}_amd64.deb
  #       sudo apt install ./comiccoin-wallet_{{.VERSION}}_amd64.deb
  #       ```
  #
  #       ## Fedora/RHEL:
  #       ```bash
  #       wget https://example.com/downloads/comiccoin-wallet-{{.VERSION}}-1.x86_64.rpm
  #       sudo dnf install ./comiccoin-wallet-{{.VERSION}}-1.x86_64.rpm
  #       ```
  #
  #       ## Verify Checksum (Optional)
  #       ```bash
  #       sha256sum -c SHA256SUMS
  #       ```
  #       EOL

  package:
    desc: Create DEB and RPM packages with checksums
    deps: [buildlinux, create-desktop, create-install-instructions]
    cmds:
      # Create dist directory
      - mkdir -p dist

      # Create packages
      - nfpm pkg --packager deb --target dist/{{.APP_NAME}}_{{.VERSION}}_amd64.deb
      - nfpm pkg --packager rpm --target dist/{{.APP_NAME}}-{{.VERSION}}-1.x86_64.rpm

      # Create checksums
      - cd dist && sha256sum * > SHA256SUMS

      # Clean up temporary files
      - rm -f desktop.desktop

      # Print output location
      - |
        echo "Created in dist/:"
        echo "- {{.APP_NAME}}_{{.VERSION}}_amd64.deb    (Ubuntu/Debian)"
        echo "- {{.APP_NAME}}-{{.VERSION}}-1.x86_64.rpm (Fedora/RHEL)"
        echo "- SHA256SUMS                              (Checksums)"
    # echo "- README.md                               (Install Instructions)"

  clean:
    desc: Clean everything
    cmds:
      - rm -rf dist build desktop.desktop
