#############
# HOW TO USE:
#############
# The purpose of this docker-compose is to setup our application which is
# dependent on the `IPFS` database cluster running concurrently with this
# server for user-acceptance testing purposes.
#
# ------------------------------------------------------------------------------
# $ docker-compose -p comiccoin_nftstorage -f docker-compose.yml up   #
# ------------------------------------------------------------------------------
#

services:
  caddy:
    container_name: comiccoin_nftstorage_caddy
    image: 'caddy:2-alpine'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '$PWD/Caddyfile:/etc/caddy/Caddyfile'
      - 'caddy_data:/data'
      - 'caddy_config:/config'
    networks:
      - web
      - internal

  ipfs-node:
    container_name: comiccoin_nftstorage_ipfs_node
    image: ipfs/kubo:master-latest
    restart: unless-stopped
    volumes:
      - ./data/ipfs:/data/ipfs
      - ./data/ipfs:/ipfs
      - ./data/ipfs:/ipns
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/data/ipfs
    ports:
      - "4001:4001" # default libp2p swarm port - should be open to public for all nodes if possible
      # - "5001:5001" # API port - provides write/admin access to the node, shouldn't be exposed at all
      # - "8080:8080" # Gateway + read only API subset - quite safe to expose, but operating public gateway may still be a risk in some ways

      # The following ports only listen on the loopback interface, so are not remotely reachable by default.
      # If you want to override these or add more ports, see https://docs.docker.com/compose/extends/ .

      # API port, which includes admin operations, so you probably don't want this remotely accessible.
      - 127.0.0.1:5001:5001

      # HTTP Gateway
      - 127.0.0.1:8080:8080
      - 127.0.0.1:8081:8081
    networks:
      - internal

  # The main application.
  app:
    container_name: comiccoin_nftstorage
    stdin_open: true
    environment:
       COMICCOIN_NFTSTORAGE_APP_DATA_DIRECTORY: ${COMICCOIN_NFTSTORAGE_APP_DATA_DIRECTORY}
       COMICCOIN_NFTSTORAGE_APP_SECRET_KEY: ${COMICCOIN_NFTSTORAGE_APP_SECRET_KEY}
       COMICCOIN_NFTSTORAGE_APP_HMAC_SECRET: ${COMICCOIN_NFTSTORAGE_APP_HMAC_SECRET}
       COMICCOIN_NFTSTORAGE_APP_API_KEY: ${COMICCOIN_NFTSTORAGE_APP_API_KEY}
       COMICCOIN_NFTSTORAGE_ADDRESS: ${COMICCOIN_NFTSTORAGE_ADDRESS}
       COMICCOIN_NFTSTORAGE_IPFS_IP: ipfs-node
       COMICCOIN_NFTSTORAGE_IPFS_PORT: 5001
       COMICCOIN_NFTSTORAGE_IPFS_PUBLIC_GATEWAY: https://ipfs.io
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "9000:9000"
    depends_on:
      - ipfs-node
    links:
      - ipfs-node
    volumes: # Connect the local filesystem with the docker filesystem. DO NOT REMOVE.
      - ./:/go/src/github.com/LuchaComics/monorepo/native/desktop/comiccoin-nftstorage # IMPORTANT: Required for hotreload via `CompileDaemon`.
    cap_add: # See: https://github.com/AdguardTeam/AdGuardHome/issues/5903
      - NET_ADMIN
    networks:
      - internal

networks:
  web:
    external: true
  internal:
    external: false
    driver: bridge

volumes:
  ipfs_data:
  caddy_data:
  caddy_config:
