// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BurnToken(arg1, arg2, arg3) {
  return window['go']['main']['App']['BurnToken'](arg1, arg2, arg3);
}

export function CreateWallet(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateWallet'](arg1, arg2, arg3);
}

export function DefaultComicCoinAuthorityAddress() {
  return window['go']['main']['App']['DefaultComicCoinAuthorityAddress']();
}

export function DefaultComicCoinNFTStorageAddress() {
  return window['go']['main']['App']['DefaultComicCoinNFTStorageAddress']();
}

export function DefaultWalletAddress() {
  return window['go']['main']['App']['DefaultWalletAddress']();
}

export function ExportWalletMnemonicPhrase(arg1, arg2) {
  return window['go']['main']['App']['ExportWalletMnemonicPhrase'](arg1, arg2);
}

export function ExportWalletUsingDialog(arg1) {
  return window['go']['main']['App']['ExportWalletUsingDialog'](arg1);
}

export function GetBlockDataByBlockTransactionTimestamp(arg1) {
  return window['go']['main']['App']['GetBlockDataByBlockTransactionTimestamp'](arg1);
}

export function GetDataDirectoryFromDialog() {
  return window['go']['main']['App']['GetDataDirectoryFromDialog']();
}

export function GetDataDirectoryFromPreferences() {
  return window['go']['main']['App']['GetDataDirectoryFromPreferences']();
}

export function GetDefaultDataDirectory() {
  return window['go']['main']['App']['GetDefaultDataDirectory']();
}

export function GetIsBlockhainNodeRunning() {
  return window['go']['main']['App']['GetIsBlockhainNodeRunning']();
}

export function GetNFTStorageAddressFromPreferences() {
  return window['go']['main']['App']['GetNFTStorageAddressFromPreferences']();
}

export function GetNonFungibleToken(arg1) {
  return window['go']['main']['App']['GetNonFungibleToken'](arg1);
}

export function GetNonFungibleTokensByOwnerAddress(arg1) {
  return window['go']['main']['App']['GetNonFungibleTokensByOwnerAddress'](arg1);
}

export function GetPreferences() {
  return window['go']['main']['App']['GetPreferences']();
}

export function GetRecentTransactions(arg1) {
  return window['go']['main']['App']['GetRecentTransactions'](arg1);
}

export function GetTotalCoins(arg1) {
  return window['go']['main']['App']['GetTotalCoins'](arg1);
}

export function GetTotalTokens(arg1) {
  return window['go']['main']['App']['GetTotalTokens'](arg1);
}

export function GetTransactions(arg1) {
  return window['go']['main']['App']['GetTransactions'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportWalletUsingDialog() {
  return window['go']['main']['App']['ImportWalletUsingDialog']();
}

export function IsSyncing() {
  return window['go']['main']['App']['IsSyncing']();
}

export function ListAllPendingSignedTransactions() {
  return window['go']['main']['App']['ListAllPendingSignedTransactions']();
}

export function ListWallets() {
  return window['go']['main']['App']['ListWallets']();
}

export function SaveDataDirectory(arg1) {
  return window['go']['main']['App']['SaveDataDirectory'](arg1);
}

export function SavePreferences(arg1) {
  return window['go']['main']['App']['SavePreferences'](arg1);
}

export function SetAuthorityAddress(arg1) {
  return window['go']['main']['App']['SetAuthorityAddress'](arg1);
}

export function SetDefaultWalletAddress(arg1) {
  return window['go']['main']['App']['SetDefaultWalletAddress'](arg1);
}

export function SetNFTStorageAddress(arg1) {
  return window['go']['main']['App']['SetNFTStorageAddress'](arg1);
}

export function ShutdownApp() {
  return window['go']['main']['App']['ShutdownApp']();
}

export function TransferCoin(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['TransferCoin'](arg1, arg2, arg3, arg4, arg5);
}

export function TransferToken(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TransferToken'](arg1, arg2, arg3, arg4);
}
