// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function CreateToken(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<domain.Token>;

export function GetDataDirectoryFromDialog():Promise<string>;

export function GetDataDirectoryFromPreferences():Promise<string>;

export function GetDefaultDataDirectory():Promise<string>;

export function GetFileViaIPFS(arg1:string):Promise<domain.NFTAsset>;

export function GetImageFilePathFromDialog():Promise<string>;

export function GetIsNFTAssetStoreRunning():Promise<boolean>;

export function GetNFTStoreAPIKeyFromPreferences():Promise<string>;

export function GetNFTStoreRemoteAddressFromPreferences():Promise<string>;

export function GetToken(arg1:number):Promise<domain.Token>;

export function GetTokens():Promise<Array<domain.Token>>;

export function GetVideoFilePathFromDialog():Promise<string>;

export function SaveDataDirectory(arg1:string):Promise<void>;

export function SaveNFTStoreAPIKey(arg1:string):Promise<void>;

export function SaveNFTStoreConfigVariables(arg1:string,arg2:string):Promise<void>;

export function SaveNFTStoreRemoteAddress(arg1:string):Promise<void>;

export function ShutdownApp():Promise<void>;

export function StartupApp():Promise<void>;
