// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateToken(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['CreateToken'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function GetDataDirectoryFromDialog() {
  return window['go']['main']['App']['GetDataDirectoryFromDialog']();
}

export function GetDataDirectoryFromPreferences() {
  return window['go']['main']['App']['GetDataDirectoryFromPreferences']();
}

export function GetDefaultDataDirectory() {
  return window['go']['main']['App']['GetDefaultDataDirectory']();
}

export function GetFileViaIPFS(arg1) {
  return window['go']['main']['App']['GetFileViaIPFS'](arg1);
}

export function GetImageFilePathFromDialog() {
  return window['go']['main']['App']['GetImageFilePathFromDialog']();
}

export function GetIsNFTAssetStoreRunning() {
  return window['go']['main']['App']['GetIsNFTAssetStoreRunning']();
}

export function GetNFTStoreAPIKeyFromPreferences() {
  return window['go']['main']['App']['GetNFTStoreAPIKeyFromPreferences']();
}

export function GetNFTStoreRemoteAddressFromPreferences() {
  return window['go']['main']['App']['GetNFTStoreRemoteAddressFromPreferences']();
}

export function GetToken(arg1) {
  return window['go']['main']['App']['GetToken'](arg1);
}

export function GetTokens() {
  return window['go']['main']['App']['GetTokens']();
}

export function GetVideoFilePathFromDialog() {
  return window['go']['main']['App']['GetVideoFilePathFromDialog']();
}

export function SaveDataDirectory(arg1) {
  return window['go']['main']['App']['SaveDataDirectory'](arg1);
}

export function SaveNFTStoreAPIKey(arg1) {
  return window['go']['main']['App']['SaveNFTStoreAPIKey'](arg1);
}

export function SaveNFTStoreConfigVariables(arg1, arg2) {
  return window['go']['main']['App']['SaveNFTStoreConfigVariables'](arg1, arg2);
}

export function SaveNFTStoreRemoteAddress(arg1) {
  return window['go']['main']['App']['SaveNFTStoreRemoteAddress'](arg1);
}

export function ShutdownApp() {
  return window['go']['main']['App']['ShutdownApp']();
}

export function StartupApp() {
  return window['go']['main']['App']['StartupApp']();
}
